baseURL = "https://example.com"
languageCode = "en-us"
title = "Parenting Quotient"
theme = "sprout-hugo-theme"
[pagination]
  pagerSize = 6

[params]
  description = "Empowering parents with knowledge, tools, and a supportive community to raise the next generation of changemakers."

  [params.mailerlite]
    apiKey = "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiI0IiwianRpIjoiODNjNGQzOTliZDQ3M2ViZGYxNzNiY2ZjNjhkN2Y3ZDcyNGJiZWQ5NzQ4MzY5ODk3OGIwMmZkNDQwYzg2NzJmNTlmOTIzMmIxOGE3OTFhYWUiLCJpYXQiOjE3Njk1MTUzNDMuMTc5ODEyLCJuYmYiOjE3Njk1MTUzNDMuMTc5ODE4LCJleHAiOjQ5MjUxODg5NDMuMTUwNDY3LCJzdWIiOiIyMDg1NDUwIiwic2NvcGVzIjpbXX0.REpmWuXIg0iQowJi5AdrdOJIgaofgqtGgZ9hp222jgDdbh_IIB3aqgvJqFd0UeKzOZ94n_Iki_NlGvq5Hm8zdmZ_LHn2izoOAVFXXy0EJeYQRsjix_aIN38pgDQI2dyTSfgvZGIrsBd4VQZLGsVBGhRclxs-OrgDsNCJFA_vgRFRzL8ntV6m5lOJaCnTWr33me6TrFVVfUsGim8Z8WfcIJSBDSGo-lbWgEN4UDuFLXub97YXNSRy1tzTIclgGSc7BfloGeRgpNOu2H_41Bod09fxEMUkF6nno-mChafk7y8UMKJykkSeRGQegdhPd3c3kSEtB3XALECPZtUIIfW5mq_cIwJ6Y7_kJB2vosSvZUm1wmNIqEhyuN6CvcXj9SXv7tIO73qoXqoERw7hWt9qR_kWBm-b5hKDV5zeguwNA4SLF-b9zlSw9pI9v5aGnQjcPZHaaZEA6viukbbvJxJvGFSB-wtx239RFHr9eo_4b0qmW_0M8MGc3VX5hWMkCx0uSYbqdBFX6DyceyFHk7yW_mw4Z8xTMSaeib4yt-fdR_4YjfAhF56qghZJo87aPUsWyPrpcrm64ljEzfP5iKIxhz-I48Sp_bY_4W2-bx97-JIh8LAFUJT_RY0MbV5a7UZNs9df0ktUQIRR1n1CE38kYwj0lT8LBBKuLk8pdG-LhrA"
    groupId = "177748474366788776"

  [params.contact]
    email = "hello@parentingquotient.com"
    address = "123 Family Lane, Parentville"

  [params.socials]
    facebook = "#"
    twitter = "#"
    instagram = "#"
    linkedin = "#"

[taxonomies]
  tag = "tags"
  category = "categories"

[menu]
  [[menu.main]]
    name = "About Us"
    url = "/about"
    weight = 1

  [[menu.main]]
    name = "Blogs"
    url = "/posts/"
    weight = 2
